import numpy as np

""" 

This portion exists to isolate the quantsim object creation from numpy calculations. this script will accept any form of quantsim, and will run a simulation based on the predefined object properties of the quantsim.

This is where experimental parameters are important, the user will define for what values of x and t should the simulation run over, what the dx and dt values will be, and overall control everything that is related to the simulation of the system.


- simulation parameters
    - [sq well] how many modes to show, if any
    - [sq well] potential well, depth
    - [tunneling particle] potential barrier height, thickness
    - [free particle] use wavepacket or not
"""

def load_obj(quantsim):
    """
    This method will load any quantsim object, and save its system information as local variables within this script
    
    Parameters
    ----------
    quantsim - QuantSim object
        should be generated by QuantSimObj.py, then fed into this script
        
    Returns
    -------
    wasSuccessful - bool
        True if object was loaded successfully, False if not.
    
    """
    return wasSuccessful


def set_exp_vals(quantsim):
    """
    This method will set experimental values
    """
    return

def set_sim_params(quantsim):
    """ 
    This
    """

def simulate(quantsim):
    
    return
