import numpy as np

""" 

This portion exists to isolate the quantsim object creation from numpy calculations. this script will accept any form of quantsim, and will run a simulation based on the predefined object properties of the quantsim.

This is where experimental parameters are important, the user will define for what values of x and t should the simulation run over, what the dx and dt values will be, and overall control everything that is related to the simulation of the system.


- simulation parameters
    - [sq well] how many modes to show, if any
    - [sq well] potential well, depth
    - [tunneling particle] potential barrier height, thickness
    - [free particle] use wavepacket or not
"""

def load_obj(quantsim):
    """
    This method will load any quantsim object, and save its system information as local variables within this script
    
    Parameters
    ----------
        quantsim - QuantSim object
            should be generated by QuantSimObj.py, then fed into this script
        
    Returns
    -------
        wasSuccessful - bool
            True if object was loaded successfully, False if not.
    
    """
    return wasSuccessful


def set_sim_params(quantsim):
    """ 
    This method will prompt user for simulation parameters.
    
    Parameters
    ----------
        quantsim - QuantSim object
            should be generated by QuantSimObj.py, then fed into this script
        
    Returns
    -------
    None
    
    """
    
    choice = quantsim.sys
        
    # prompt user for how to choose simulation parameters
    use_default = input("""\nWould you like to enter custom experimental values, or use the default?: 
                           \n    Enter 1 for default, 0 for manual entry: """)
    if use_default == "1":
       # determine the system, then set experimental values accordingly
       # start with experimental values shared by all systems
       # add extra values by dict[key] = value assignment
       
        quantsim.sim_params = {
           'dx' : quantsim.exp_vals[length]/100,  # 100 data points
           'dt' : 0.01, 
        }  
       
        # go through each system's unique values
        if choice in ["1", "Infinite Square Well", "ISW"]:
            # no extra parameters
            pass    
        elif choice in ["2", "Finite Square Well", "FSW"]:
            # no extra parameters
            pass    
        elif choice in ["3", "Quantum Harmonic Oscillator", "QHO"]:
            # no extra parameters
            pass
        else:
            print("\nSystem not found. Please retry.\n")
            set_sim_params(quantsim)  # restart method
           
    print("Set experimental values to default. Use quantsim.info() to inspect!")
        
        
    elif use_default == "0":
        print("Manual implementation WIP.")
        set_sim_params(quantsim)  # restart method
        
    else:
        print("Invalid entry. Please try again!\n")
        set_sim_params(quantsim) # restart method
        
            
    return 

''' begin simulation methods '''

def InfSqWell(quantsim):
    
    return

def FinSqWell(quantsim):
    
    return

def ParabSqWell(quantsim):
    
    return

def simulate(quantsim):
    """
    This method will perform numpy calculations to simulate the correct equations for each physical system. Equations and wavefunctions are hardcoded in.
    
    Parameters
    ----------
        quantsim - QuantSim object
            should be generated by QuantSimObj.py, then fed into this script
        
    Returns
    -------
        
    
    """
    
    if choice in ["1", "Infinite Square Well", "ISW"]:
        sim_soln = InfSqWell(quantsim)
        pass

    elif choice in ["2", "Finite Square Well", "FSW"]:
        sim_soln = FinSqWell(quantsim)
        pass

    elif choice in ["3", "Quantum Harmonic Oscillator", "QHO"]:
        sim_soln = ParabSqWell(quantsim)
        pass
    
    else:
        print("\nSystem not found. Please reinitialize object.\n")
    
    return
